import { StyleSheet } from 'react-native';

export const GlobalStyles = {
    colors: {
        primary50: '#67666b',
        primary100: '#302e36',
        primary200: '#2f2c38',
        primary400: '#2f2c38',
        primary500: '#312b3d',
        primary700: '#221c30',
        primary800: '#130f1c',
        accent500: '#f7bc0c',
        error100: '#fcdcbf',
        error50: '#fcc4e4',
        error500: '#9b095c',
        gray100: '#94919c',
        gray500: '#39324a',
        gray700: '#221c30',
        green10: '#DBEBDB',
        green50: '#91ba8f',
        green100: '#4b694a',
        green500: '#156b12',
        green700: '#043002',
        red10: '#EBD5DA',
        red100: '#9e777e',
        red500: '#990b25',
        font: '#FAFCF8',
        fontSecondary: '#DCDCDC',
    },
};

export const styles = StyleSheet.create({
    pressed: {
        opacity: 0.75,
    },
    rootContainer: {
        backgroundColor: GlobalStyles.colors.primary800,
    },

    form: {
        marginTop: 10,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    item: {
        padding: 12,
        marginVertical: 8,
        backgroundColor: GlobalStyles.colors.primary500,
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderRadius: 6,
        elevation: 3,
        shadowColor: GlobalStyles.colors.gray500,
        shadowRadius: 4,
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.4,
    },
    leanItem: {
        padding: 4,
        margin: 2,
    },
    rowItem: {
        flexDirection: 'column',
        justifyContent: 'flex-start',
        padding: 4,
        marginVertical: 8,
        backgroundColor: GlobalStyles.colors.primary500,
        borderRadius: 6,
        elevation: 3,
        shadowColor: GlobalStyles.colors.gray500,
        shadowRadius: 4,
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.4,
    },
    textBase: {
        color: GlobalStyles.colors.font,
    },
    description: {
        fontSize: 16,
        marginBottom: 4,
        fontWeight: 'bold',
    },
    smallDescription: {
        fontSize: 12,
        marginBottom: 4,
    },
    infoContainer: {
        flex: 4,
        padding: 10,
    },
    rowInfoContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        flex: 4,
        padding: 4,
    },
    fieldContainer: {
        flexDirection: 'row',
        marginBottom: 10,
        width: '100%',
        justifyContent: 'space-between',
    },

    amountContainer: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        backgroundColor: GlobalStyles.colors.primary50,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 4,
        minWidth: 80,
        flex: 2,
        padding: 10,
    },
    amount: {
        color: GlobalStyles.colors.font,
        fontWeight: 'bold',
    },
    container: {
        flex: 1,
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: 0,
        backgroundColor: GlobalStyles.colors.primary700,
    },
    infoText: {
        color: GlobalStyles.colors.font,
        fontSize: 16,
        textAlign: 'center',
        marginTop: 32,
    },
    containerSummary: {
        padding: 8,
        backgroundColor: GlobalStyles.colors.primary50,
        borderRadius: 6,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    period: {
        fontSize: 12,
        color: GlobalStyles.colors.font,
    },
    sum: {
        fontSize: 16,
        fontWeight: 'bold',
        color: GlobalStyles.colors.font,
    },
    title: {
        fontSize: 14,
        fontWeight: 'bold',
        color: GlobalStyles.colors.font,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        height: 56,
        paddingLeft: 25,
        paddingRight: 18,
        alignItems: 'center',
        backgroundColor: GlobalStyles.colors.gray500,
    },
    parentHr: {
        height: 1,
        color: GlobalStyles.colors.font,
        width: '100%',
    },
    child: {
        backgroundColor: GlobalStyles.colors.gray500,
        padding: 16,
    },
    green: { color: GlobalStyles.colors.green10 },
    red: {
        color: GlobalStyles.colors.red10,
    },
    bold: {
        fontWeight: 'bold',
    },
    greenBackground: {
        color: GlobalStyles.colors.green10,
        backgroundColor: GlobalStyles.colors.green700,
        minWidth: '6rem',
        textAlign: 'end',
        flex: 0,
    },
    redBackground: {
        color: GlobalStyles.colors.red10,
        backgroundColor: GlobalStyles.colors.red500,
        minWidth: '6rem',
        textAlign: 'end',
        flex: 0,
    },
    tableHeader: {
        backgroundColor: GlobalStyles.colors.gray500,
        justifyContent: 'flex-start',
        alignItems: 'center',
        color: GlobalStyles.colors.font,
    },
});
